language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - ruby-head
  - jruby
  - jruby-19mode
  - rbx
  - rbx-19mode

env:
  - MONGOID_VERSION=3
  - MONGOID_VERSION=4
  - MONGOID_VERSION=5


matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: jruby-19mode
    - rvm: rbx
    - rvm: rbx-19mode

services: mongodb
